### ISSUE TITLE
Taken to wrong workspace (as reported on reddit)

### ISSUE THREAD

**Issue by xircon** [CarloCattano/workspacer#2]
On workspace 1:
![image](https://github.com/CarloCattano/workspacer/assets/1316691/0124ec9f-55fc-4979-87ab-f2c09beb36e7)

Click on opera:
![image](https://github.com/CarloCattano/workspacer/assets/1316691/ee940028-76b5-4b00-b2fa-a9e22daed8a3)

Taken to workspace 2 not 3

**Comment by CarloCattano** [comment]
Should be fixed now , thanks!
